### ISSUE TITLE
find_start_codes never used?

### ISSUE THREAD

**Issue by jvcleave** [OtherCrashOverride/hello_videocube#1]
I think you can remove a big chunk of code as find_start_codes is never used (at least in my testing)

https://github.com/OtherCrashOverride/hello_videocube/blob/master/video.c#L241

**Comment by OtherCrashOverride** [comment]
One of the goals of the sample was to show the necessary changes from the original hello_video code to implement egl_render.  Because of this, code changes were limited to the scope of the task.  The find_start_codes is probably a vestigial remnant from pre PI days but you would have to ask the foundation about that.

This sample is becoming part of the official Raspberry Pi repo, so you can post issues there if you wish.

**Comment by jvcleave** [comment]
I actually tracked it down to here and asked the hello_video author about the implementation but haven't heard back
http://www.cnx-software.com/2012/02/18/raspberry-pi-opengl-and-openmax-il-hello-world-applications/

Congrats on getting it in the official repo! It was very helpful! For my project I ended up using omxplayer as a base as it plays other videos much more easily
